local opts = { noremap = true, silent = true }

local function map(mode, lhs, rhs, desc, extra)
	local map_opts = vim.tbl_extend("force", opts, extra or {})
	map_opts.desc = desc
	vim.keymap.set(mode, lhs, rhs, map_opts)
end

vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { silent = true })

map("n", "<C-h>", "<C-w>h", "Move to left window")
map("n", "<C-j>", "<C-w>j", "Move to bottom window")
map("n", "<C-k>", "<C-w>k", "Move to top window")
map("n", "<C-l>", "<C-w>l", "Move to right window")

map("n", "<C-Up>", "<cmd>resize -2<CR>", "Decrease window height")
map("n", "<C-Down>", "<cmd>resize +2<CR>", "Increase window height")
map("n", "<C-Left>", "<cmd>vertical resize -2<CR>", "Decrease window width")
map("n", "<C-Right>", "<cmd>vertical resize +2<CR>", "Increase window width")

map("n", "<S-l>", "<cmd>bnext<CR>", "Next buffer")
map("n", "<S-h>", "<cmd>bprevious<CR>", "Previous buffer")

map("n", "<A-j>", "<cmd>m .+1<CR>==", "Move line down")
map("n", "<A-k>", "<cmd>m .-2<CR>==", "Move line up")

map("i", "jk", "<Esc>", "Exit insert mode")
map("i", "kj", "<Esc>", "Exit insert mode")

map("v", "<", "<gv", "Indent left")
map("v", ">", ">gv", "Indent right")
map("v", "<A-j>", ":m '>+1<CR>gv=gv", "Move selection down")
map("v", "<A-k>", ":m '<-2<CR>gv=gv", "Move selection up")
map("v", "p", '"_dP', "Paste without yanking")

map("x", "J", ":move '>+1<CR>gv-gv", "Move block down")
map("x", "K", ":move '<-2<CR>gv-gv", "Move block up")
map("x", "<A-j>", ":move '>+1<CR>gv-gv", "Move block down")
map("x", "<A-k>", ":move '<-2<CR>gv-gv", "Move block up")

map("t", "<C-h>", "<C-\\><C-N><C-w>h", "Move to left window")
map("t", "<C-j>", "<C-\\><C-N><C-w>j", "Move to bottom window")
map("t", "<C-k>", "<C-\\><C-N><C-w>k", "Move to top window")
map("t", "<C-l>", "<C-\\><C-N><C-w>l", "Move to right window")

map("n", "K", vim.lsp.buf.hover, "LSP: hover documentation")
map("n", "gl", vim.diagnostic.open_float, "LSP: line diagnostics")
map("n", "<leader>lf", function()
	vim.lsp.buf.format({ async = true })
end, "LSP: format document")
map("n", "<leader>li", "<cmd>LspInfo<cr>", "LSP: server information")
map("n", "<leader>lj", function()
	vim.diagnostic.jump({ count = 1, float = true })
end, "LSP: next diagnostic")
map("n", "<leader>lk", function()
	vim.diagnostic.jump({ count = -1, float = true })
end, "LSP: previous diagnostic")
map("n", "<leader>lr", vim.lsp.buf.rename, "LSP: rename symbol")
map("n", "<leader>ls", vim.lsp.buf.signature_help, "LSP: signature help")
map("n", "<leader>lq", vim.diagnostic.setloclist, "LSP: diagnostics to location list")

map("n", "<F8>", function()
	require("dap").toggle_breakpoint()
end, "Debug: toggle breakpoint")
map("n", "<F7>", function()
	require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, "Debug: conditional breakpoint")
map("n", "<F5>", function()
	require("dap").continue()
end, "Debug: continue")
map("n", "<F3>", function()
	require("dapui").toggle()
end, "Debug: toggle UI")
map("n", "<F4>", function()
	require("dapui").eval(nil, { enter = true })
end, "Debug: evaluate expression")
map("n", "<F10>", function()
	require("dap").step_into()
end, "Debug: step into")
map("n", "<F9>", function()
	require("dap").step_over()
end, "Debug: step over")
map("n", "<S-F9>", function()
	require("dap").step_out()
end, "Debug: step out")
map("n", "<leader>du", function()
	require("dapui").toggle()
end, "Debug: toggle UI")
map("n", "<leader>q", function()
	require("dap").terminate()
end, "Debug: terminate session")
map("n", "<space>?", function()
	require("dapui").eval(nil, { enter = true })
end, "Debug: evaluate expression")
